### ISSUE TITLE
Difference between the original mask-rcnn and mt-mrcnn model.

### ISSUE THREAD

**Issue by iamheidi** [noxouille/rt-mrcnn#2]
Hello.
What is the big difference between the original mask-rcnn and mt-mrcnn? Are the two model structures different? How did you speed up? Is it possible to explain? Is only run_webcam.py code different?

**Comment by iamheidi** [comment]
i found just use small size image.

**Comment by noxouille** [comment]
Hi!
This repo is in principle a mask-rcnn running live from webcamera feed.
Although there is no significant improvements from the core architecture of mask-rcnn itself, I find it useful to illustrate the concept of mask-rcnn as a simple demo program with decent enough performance, as it is more interesting to look at a live demo instead of offline processing.

And yes, only run_webcam.py code is different so far.
